---
title: "Getting Started with R & RStudio"
---


This course will make **extensive** use of the [R programming language]() through the [RStudio](https://posit.co/download/rstudio-desktop/) integrated development environment (IDE). 
Because the formal pre-requisites for this course are STAT 333 or 340, you are expected to have previous experience using the R programming language.

:::{#prereq-warning .callout-important}

## Warning

I will assume *fluency* with basic R functionality (e.g., assignment, writing and
executing scripts, saving data objects, setting environments, installing and loading packages), data manipulation with **dplyr** and other **tidyverse** packages, and visualization using either base R graphics or **ggplot2**. 
I will additionally assume some familiarity with fitting statistical models in
R and interpreting their output (e.g., using `lm` and `glm`).

If you do **not** meet the formal course prerequisites and/or have not used R in a previous course, this is **not** the right course for you. 
:::



### Additional R resources

Having issued that warning @prereq-warning, you will see some new R functionality in the course.
As the focus is on answer sports problems, we will not spend significant classtime going over new functions, packages, or techniques.
If you find that there are gaps in your R knowledge, you are expected to fill them on your own time.
Here are some helpful resources

  * [R for Data Science](https://r4ds.hadley.nz)
  * [Data Science: A first introduction](https://datasciencebook.ca)

## Installation

While you are expected to have used R in previous courses (see warning), I **strongly** recommend installing the latest version of both R and RStudio at the beginning of the course.
As of the time of this writing, that is R version 4.5 and RStudio version 2025.05.

You can download a version of R specific to for your operating system from [this website](https://cloud.r-project.org).


### Package re-installation

Whenever you update your version of R, you need to re-install the packages; this is a perennial source of [frustration](https://bsky.app/profile/benbushong.com/post/3lbqnkbazgh2e) for many R users] and [some good-natured humor](https://bsky.app/profile/hadley.nz/post/3lnlrbqv7qs2i) from others (who [also](https://bsky.app/profile/hadley.nz/post/3lnmafh3ljs2y) manually re-installs packages after every update!)



## Required Packages

Throughout the course, we will make extensive use of several packages in the **tidyverse**, primarily for data loading, pre-processing, and manipulation.
We will also make extensive use of the packages **glmnet**, **ranger**, and **xgboost** for model fitting.
We will occassionally also use **ggplot2** for creating visualizations.

As the course progresses, we will introduce and install new package as required.
For the most part, these packages will be specific to a particular sport (e.g., in Lecture 1 we will use the [**nbastatR**](http://asbcllc.com/nbastatR/index.html) to access NBA player box-score statistics).

Every package that we will use in this class is available through either (i) the  Comprehensive R Archive Network (CRAN) or (ii) a public GitHub repository maintained by the packager developer.
We typically install CRAN packages using the `install.packages()` command.
To install packages hosted on GitHub, we will use the `install_github` function in the [*devtools*](https://cran.r-project.org/web/packages/devtools/index.html) package (which itself is available on CRAN)

:::{.callout-tip}
## Required installations

Prior to Lecture 2, please make sure you have installed the **tidyverse** packages as well as **devtools**, **ggplot2**, **glmnet**, **ranger**, and **xgboost**.
```{r install_packages}
#| eval: false
install.packages(c("devtools", "tidyverse", "ggplot2", 
                   "glmnet", "ranger", "xgboost"))
```
:::




