---
title: "Lecture 13: Power Rankings II"
format: html
execute: 
  cache: true
---


## Motivation: Power rankings

## The basic Bradley-Terry model


### Estimation

Conveniently, there is a nice R package **BradleyTerry2* that allows

## Example:

## From estimation to simulation

While estimating these model parameters is nice, how might be **use** them prospectively?

One idea is to *simulate*.

Given estimates $\hat{\lambda},$ we can look at a series of matches and try to forecast.

<!-- e.g., use nba power rankings to simulate what happens over the course a; potential project idea is to do this for CFP or march maddnes -->


## Going beyond the basic model

There are many many extensions of the model. Here are just a handful.


The basic BT model does not account for ties, making it difficult to apply, e.g., to professional soccer (football outside America).



One could envision fitting a Bradley-Terry model to each 

### Multi-level BT models

It could very well be the case that $\lambda_{t}$ depends on factors related to the team $t$ (e.g., its payroll, number of all-star players, strenght of schedule to date, etc).
The **BradleyTerry2** package allows us to fit multi-level models in which $\lambda_{t}$ is allowed to depend on covariates in a linear fashion.




