---
title: "Lecture 1: Boxscore Metrics"
format: html
---

## Overview
Who is the best shooter in the NBA?

How do we determine this *using data*?
<!--
 Main questions: who is the best shooter in the NBA? 
 How might we use *data* to determine this? 
-->

### Retrospective vs prospective Metrics




### Key Topics


In this lecture, we will practice using functions from the **tidyverse** suite of packages (especially **dplyr**) to manipulate tables of NBA box score data.
Hopefully, much of the functionality we encounter in this lecture will be familiar to you.
But, if you need a high-level refresher, I highly recommend the following resources:

  * [Chapter 3](https://r4ds.hadley.nz/data-transform.html) and [Chapter 5]() of [*R for Data Science*](https://r4ds.hadley.nz).
  * [Section 1.9](https://datasciencebook.ca/intro.html#adding-and-modifying-columns-using-mutate) and [Chapter 3](https://datasciencebook.ca/wrangling.html) of [*Data Science: A First Introduction](https://datasciencebook.ca). 

We will use

:::{#nbastatR-install .callout-important collapse="true"}
## System setup

For this lecture, we will use a new R package to scrape NBA boxscore data.
In order to do this, it is critical that you have already installed the **devtools** package, as noted in the [Getting Started guide](guides/getting_started.html).
To check that you have successfully installed the package, run the following code.
```{r}
if(!"devtools" %in% rownames(installed.packages())){
  stop("devtools not installed")
}
```
:::


## Initial metrics

### Scraping box score data using **


<!--
 Load in box score data using
-->


