---
title: "Lecture 2: Expected Goals in Soccer"
format: html
execute: 
  cache: true
---

## Motivation: Beth Meade's Performance at EURO2022

Consider the following goals scored by Beth Meade during EURO 2022.


:::: {.columns}

:::{.column width="49%"}
{{< video https://youtube.com/clip/UgkxS9IXis1jcLq7Q5oTB2ED6Dkb34FT7TmM?si=-2MwgWJsy2HkeWgb >}}

:::

:::{.column width="49%"}
{{< video https://youtube.com/clip/UgkxJKtmAvMQ9eXTygNxJUkLL1BvVN7o2njn?si=TUaiNTdkohxUWfqr >}}
:::

::::


We can make these statements more quantiatively precise using *expected goals*

Definition of xG

## Digression: Conditional Probability

<!--
  1. Statistically, xg is an example of conditional probability
  2. Notationally it is written like this. On the left ofthe bar
  3. One way to compute this is to divide. Example: P(goal | footedness or play-type)
  4. In the examples above, we want to condition on many more variables. This involves doing something more sophisticated than simple binning & averaging. We usually fit a model (stay tuned)
-->


## Working with StatsBomb's XG

<!--
  1. There are many existing xg models. They differ in terms of (i) the covariates (i.e., what goes on the right hand side of the conditioning statement) and (ii) the estimation procedure. We will explore different ones next lecture
  2. For today, we will use XG provided by StatsBomb
  3. Load up the data; focus on EURO 2022 only
-->

As an illustration, here is a visualization of all of Beth Meade's shots along with the associated XG value. Notice that some are very low and some are very high.


## Goals Above Expected (Team-Based)

## Goals Above Expected (Player-Based)

<!--
  We see that in the first goal, Meade's XG was quite high. So, in some sense, we might want to give her much less credit.
  Summing over all her shots, we can get a sense of 
  
-->

Mathematically, let $Y_{ij}$ be the outcome of shot $j$ taken by player $i$ with $Y_{ij} = 1$ if a goal is scored off that shot and $Y_{ij} = 0$ otherwise.
Additionally $\textrm{XG}_{ij}$ be the corresponding XG value for that shot.





We can compute the difference $y_{ij} - \textrm{xg}_{ij}$ for each shot that player $i$ takes 


