project:
  type: website
  output-dir: ../docs

website:
  title: "STAT479"
  navbar:
    background: "primary"
    foreground: "secondary"
    left:
      - text: "Home"
        href: index.qmd
        
      - sidebar:lectures
      - sidebar:exercises
      - sidebar:guides
      
  sidebar:
    - id: lectures
      title: "Lectures"
      style: "docked"
      background: light
      collapse-level: 2
      contents: "lectures/*.qmd"
      
    - id: exercises
      title: "Exercises"
      contents: "exercises/*.qmd"      
        
    - id: guides
      title: "Guides"
      contents: "guides/*.qmd"
    
format:
  html:
    #theme: cosmo
    #css: uw-style.css
    css: styles.css
    toc: true
brand: _brand.yml


