project:
  type: website
  output-dir: ../docs

website:
  title: "STAT479"
  navbar:
    background: primary
    left:
      - text: "Home"
        href: index.qmd
      - text: "Lectures"
        href: lectures.qmd
      - text: "Guides"
        href: guides.qmd
      - text: "Exercises"
        href: exercises.qmd
        
  sidebar:
    - title: "Lectures"
      style: "docked"
      background: light
      contents: 
        - lectures/lecture1.qmd
        
    - title: "Exercises"
      contents: "exercises/*.qmd"
      
    - title: "Guides"
      contents: "guides/*.qmd"
format:
  html:
    theme: cosmo
    #css: uw-style.css
    css: styles.css
    toc: true



