project:
  type: website
  output-dir: ../docs

website:
  title: "STAT479"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Lectures"
        href: lectures.qmd
      - text: "Exercises"
        href: exercises.qmd
    sidebar:
      - title: "Lectures"
        style: "docked"
        background: light
        contents: lectures/*
      - title: "Exercises"
        contents: exercises/*

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



