project:
  type: website
  output-dir: ../docs
  resources:
   - raw_slides/*


website:
  title: "STAT479"
  navbar:
    background: "#C5050C"
    foreground: "#FFFFFF"
    left:
      - text: "Home"
        href: index.qmd
      - text: "Syllabus"
        href: syllabus.qmd        
      - sidebar:lectures
      - sidebar:slides
      #- sidebar:exercises
      #- sidebar:guides
      
  sidebar:
    - id: lectures
      title: "Lecture Code"
      style: "docked"
      background: light
      collapse-level: 2
      contents: "lectures/*.qmd"
    - id: slides
      title: "Lecture Slides"
      style: "docked"
      background: light
      collapse-level: 2
      contents: "slides/*.qmd"
      
   # - id: exercises
   #   title: "Exercises"
   #   contents: "exercises/*.qmd"      
        
   # - id: guides
   #   title: "Guides"
   #   contents: "guides/*.qmd"
    
format:
  html:
    theme: [cosmo, styles.scss]
    css: styles.css
    toc: true

execute:
  cache: true
code-annotations: hover 
code-overflow: wrap
bibliography: lectures/stat479_refs.bib
lightbox: true
