---
title: "STAT 479 (Fall 2025): Sports Analytics"
---

Welcome to STAT 479 (Special Topics in Statistics)!
This iteration of the course will focus on sports analytics.

Lectures notes, instructions for the course project, and additional tutorials and exercises will be posted to this website.
So, please bookmark this page and check it regularly throughout the course.

## Course information

**Description**: Illustrates the use of statistical modeling and data science techniques to derive actionable insights from sports data. Emphasizes not only technical calculation of advanced metrics but also on written and oral communication to other data scientists and to non-technical audience. Topics may include: deriving team rankings from paired competitions; measuring an individual player's contribution to their team's overall success; assessing player performance and team strategy in terms of expected outcomes; forecasting the impact of new rule changes using simulation; and creating new metrics using high-resolution player tracking data.

**Learning Outcomes**: Throughout the course you will 
  1. Implement appropriate statistical methods to assess player and team performance
  2. Work with play-by-play and high-resolution tracking data
  3. Provide constructive and actionable feedback on your peers' analytic reports
  4. Build a personal portfolio of sports data analyses
  
**Location & Schedule:** Tuesdays & Thursdays, 11:00am-12:15pm, 1524 Morgridge Hall

**Instructor & Office Hours:** [Sameer Deshpande](https://skdeshpande91.github.io) (sameer.deshpande@wisc.edu). Office Hours TBA.



